name:                hYGG
version:             0.1.0.0
github:              "githubuser/hYGG"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hYGG#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- Spock
- text
- http-types
- hxt
- hxt-curl
- extra
- uri-encode
- parallel-io
- time
- network-uri
- lens
- wreq
- bytestring
- wai
- split

data-dir: res
data-files: ./*

library:
  source-dirs: src

executables:
  hYGG:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hYGG

tests:
  hYGG-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hYGG
